---
- hosts: kube-master

  tasks:
  - name: Check the API servers are responding
    local_action:
      module: uri
      url: https://{{ ansible_ssh_host }}/api/v1
      user: kube
      password: changeme
      validate_certs: no
      status_code: 200
