---
- hosts: kube-node[0]

  vars:
    kubectl_path: "/usr/local/bin/kubectl"

  tasks:
  - name: Run a replica controller composed of 2 pods
    shell: "{{kubectl_path}} run test --image=busybox --replicas=2 --command -- tail -f /dev/null"

  - name: Pods are running
    shell: "{{kubectl_path}} get pods --no-headers -o json"
    register: run_pods_log
    until: [ '(run_pods_log.stdout | from_json)["items"] | map(attribute = "status.phase") | join(",") == "Running,Running"' ]
    retries: 24
    delay: 5
