---
- hosts: all
  sudo: False
  gather_facts: no

  tasks:

    - name: delete gce instances
      local_action:
        module: gce
        name: "{{ inventory_hostname }}"
        service_account_email: "{{ gce_service_account_email }}"
        pem_file: "{{ gce_pem_file }}"
        project_id: "{{ gce_project_id }}"
        state: 'absent'
